<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Clustering.SPC</RootNamespace>
    <AssemblyName>Clustering.SPC</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\src\clustering\spc\**\*.cs" Link="spc\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Graphs.Primitives\Graphs.Primitives.csproj" />
    <ProjectReference Include="..\Graphs.Proximity\Graphs.Proximity.csproj" />
    <ProjectReference Include="..\Maths.Information\Maths.Information.csproj" />
    <ProjectReference Include="..\Maths.Rng\Maths.Rng.csproj" />
  </ItemGroup>
</Project>
