<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>LinearAlgebra</RootNamespace>
    <AssemblyName>LinearAlgebra</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\src\linalg\*.cs" Link="linalg\%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
