<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>VizCoreSmoke</RootNamespace>
    <AssemblyName>VizCoreSmoke</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VizCore\VizCore.csproj" />
  </ItemGroup>
</Project>
