<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Graphs.Proximity</RootNamespace>
    <AssemblyName>Graphs.Proximity</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\src\graphs\Bandwidth.cs" Link="graphs\Bandwidth.cs" />
    <Compile Include="..\..\src\graphs\diagnostics\*.cs" Link="graphs\diagnostics\%(Filename)%(Extension)" />
    <Compile Include="..\..\src\graphs\GraphBuilder.cs" Link="graphs\GraphBuilder.cs" />
    <Compile Include="..\..\src\graphs\GraphSelection.cs" Link="graphs\GraphSelection.cs" />
    <Compile Include="..\..\src\graphs\proximity\*.cs" Link="proximity\%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Graphs.Primitives\Graphs.Primitives.csproj" />
    <ProjectReference Include="..\Graphs.Coupling\Graphs.Coupling.csproj" />
    <ProjectReference Include="..\Maths.LinAlg\Maths.LinAlg.csproj" />
    <ProjectReference Include="..\TDA.Primitives\TDA.Primitives.csproj" />
  </ItemGroup>
</Project>
