<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Estimators</RootNamespace>
    <AssemblyName>Estimators</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Numerics.Tensors" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\src\estimators\**\*.cs" Link="estimators\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Maths.Geometry\Maths.Geometry.csproj" />
    <ProjectReference Include="..\Maths.Optimization\Maths.Optimization.csproj" />
  </ItemGroup>
</Project>
