<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Hashish</RootNamespace>
    <AssemblyName>Hashish</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\src\hashish\*.cs" Link="hashish\%(Filename)%(Extension)" />
  </ItemGroup>
</Project>