<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>SpcCore</RootNamespace>
    <AssemblyName>SpcThermo</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\src\clustering\spc\spc.thermo.cs" Link="spc\spc.thermo.cs" />
    <Compile Include="..\..\src\clustering\spc\thermo\*.cs" Link="spc\thermo\%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SpcCore\SpcCore.csproj" />
  </ItemGroup>
</Project>
