<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>DistanceMetrics</RootNamespace>
    <AssemblyName>DistanceMetrics</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\src\metrics\*.cs" Link="metrics\%(Filename)%(Extension)" />
    <Compile Include="..\..\src\manifolds\geodesics\FisherRaoSimplex.cs" Link="manifolds\geodesics\FisherRaoSimplex.cs" />
    <Compile Include="..\..\src\manifolds\geodesics\FisherRaoHalfPlane.cs" Link="manifolds\geodesics\FisherRaoHalfPlane.cs" />
    <Compile Include="..\..\src\manifolds\geodesics\Poincare.cs" Link="manifolds\geodesics\Poincare.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Numerics.Tensors" Version="10.0.0" />
  </ItemGroup>
</Project>
