<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Synthetic</RootNamespace>
    <AssemblyName>Synthetic</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\src\synthetic\**\*.cs" Link="synthetic\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
