<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>VizApi</RootNamespace>
    <AssemblyName>VizApi</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VizCore\VizCore.csproj" />
    <ProjectReference Include="..\SyntheticDatasets\SyntheticDatasets.csproj" />
    <ProjectReference Include="..\ProximityGraphs\ProximityGraphs.csproj" />
    <ProjectReference Include="..\StatisticalEstimators\StatisticalEstimators.csproj" />
    <ProjectReference Include="..\DistanceMetrics\DistanceMetrics.csproj" />
  </ItemGroup>
</Project>
