<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Maths.LinAlg</RootNamespace>
    <AssemblyName>Maths.LinAlg</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\src\maths\linalg\*.cs" Link="linalg\%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
