<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>ProximityGraphs</RootNamespace>
    <AssemblyName>ProximityGraphs</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\src\graphs\*.cs" Link="graphs\%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
