<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Spc.BlattAnalyze</RootNamespace>
    <AssemblyName>Spc.BlattAnalyze</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Clustering.SPC\Clustering.SPC.csproj" />
  </ItemGroup>
</Project>
