<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Maths.Information</RootNamespace>
    <AssemblyName>Maths.Information</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\src\maths\information\*.cs" Link="information\%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
